name: Deploy Backend

on:
  push:
    branches:
      - main

    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code from GitHub
        uses: actions/checkout@v4

      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install libraries
        working-directory: ./backend
        run: npm install

      - name: Run tests
        working-directory: ./backend
        run: npm test

  deploy:
    needs: build-and-test 
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}