name: Deploy Backend

on:
  push:
    branches:
      - main

    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn từ GitHub
        uses: actions/checkout@v4

      - name: Cài đặt Node.js phiên bản 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cài đặt các thư viện (npm install)
        working-directory: ./backend
        run: npm install

    
  deploy:
    needs: build-and-test 
    runs-on: ubuntu-latest
    steps:
      - name: Kích hoạt Deploy trên Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}